{% set version = "2.12.15" %}

package:
  name: spyne
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/spyne/spyne-{{ version }}.tar.gz
  sha256: 02d483aa7b2df9e2abb7ece413c4fc8f941a1bd7b67b4a8fde2e00b635f2c441

build:
  number: 1000
  skip: True  # [py>36]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"
  entry_points:
    - sort_wsdl = spyne.test.sort_wsdl:main

requirements:
  build:
    - python
    - pip
  run:
    - python
    - pytz
    - lxml  # [not osx]
    - zope.interface
    - sqlalchemy <1.0.99
    - pyzmq
    - werkzeug
    - pyparsing
    - twisted
    - django
    - pyramid
    - msgpack-python
    - pyyaml
    - simplejson
    - pywin32  # [win and py2k]

test:
  imports:
    - spyne
    - spyne.auxproc
    - spyne.client
    - spyne.client.twisted  # [not py3k]
    - spyne.const
    - spyne.interface
    - spyne.interface.wsdl  # [not osx]
    - spyne.interface.xml_schema  # [not osx]
    - spyne.model
    - spyne.model.primitive
    - spyne.protocol
    - spyne.protocol.cloth  # [not osx]
    - spyne.protocol.dictdoc
    - spyne.protocol.html  # [not osx]
    - spyne.protocol.soap  # [not osx]
    - spyne.server
    - spyne.server.twisted  # [not py3k]
    - spyne.store
    - spyne.store.relational
    - spyne.test
    - spyne.test.interface
    - spyne.test.interface.wsdl  # [not osx]
    - spyne.test.interop
    - spyne.test.interop.server
    - spyne.test.interop.server.soap11
    - spyne.test.interop.server.soap12
    - spyne.test.model
    - spyne.test.multipython
    - spyne.test.multipython.model
    - spyne.test.protocol
    - spyne.test.transport
    - spyne.util
    - spyne.util.oset

about:
  home: http://spyne.io
  license: LGPL-2.1
  summary: 'A transport and architecture agnostic rpc library that focuses on exposing public services with a well-defined API.'

extra:
  recipe-maintainers:
    - ocefpaf
    - emiliom
