{% set version = "2.13.15" %}

package:
  name: spyne
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/spyne/spyne-{{ version }}.tar.gz
  sha256: 379f569fa1a756307cd39dd72f31a6d6093b6ca23d174be5cc17d4f3db98793f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - sort_wsdl = spyne.test.sort_wsdl:main

requirements:
  host:
    - python
    - pip
    - colorama
    - coverage
    - pytest
    - tox
  run:
    - python
    - pytz

test:
  requires:
    - pip
    - lxml
    - zope.interface
    - sqlalchemy <1.0.99
    - pyzmq
    - werkzeug
    - pyparsing
    - twisted
    - django
    - pyramid
    - msgpack-python
    - pyyaml
    - simplejson
  imports:
    - spyne
    - spyne.auxproc
    - spyne.client
    - spyne.const
    - spyne.interface
    - spyne.interface.wsdl
    - spyne.interface.xml_schema
    - spyne.model
    - spyne.model.primitive
    - spyne.protocol
    - spyne.protocol.cloth
    - spyne.protocol.dictdoc
    - spyne.protocol.html
    - spyne.protocol.soap
    - spyne.server
    - spyne.store
    - spyne.store.relational
    - spyne.test
    - spyne.test.interface
    - spyne.test.interface.wsdl
    - spyne.test.interop
    - spyne.test.interop.server
    - spyne.test.interop.server.soap11
    - spyne.test.interop.server.soap12
    - spyne.test.model
    - spyne.test.multipython
    - spyne.test.multipython.model
    - spyne.test.protocol
    - spyne.test.transport
    - spyne.util
    - spyne.util.oset
  commands:
    - pip check
    - sort_wsdl --help

about:
  home: http://spyne.io
  license: LGPL-2.1-or-later
  license_file: LICENSE
  summary: A transport and architecture agnostic rpc library that focuses on exposing public services with a well-defined API

extra:
  recipe-maintainers:
    - ocefpaf
    - emiliom
