{% set version = "2.14.0" %}

package:
  name: spyne
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/spyne/spyne-{{ version }}.tar.gz
  sha256: 063e950e179a7d5b06b577c9f2c9091a70d40217f1a853076b3709caa2bf3a16

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - sort_wsdl = spyne.test.sort_wsdl:main

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - pytz

test:
  requires:
    - lxml
    - zope.interface
    - sqlalchemy <1.0.99
    - pyzmq
    - werkzeug
    - pyparsing
    - twisted
    - django
    - pyramid
    - msgpack-python
    - pyyaml
    - simplejson
  imports:
    - spyne
    - spyne.auxproc
    - spyne.client
    - spyne.const
    - spyne.interface
    - spyne.interface.wsdl
    - spyne.interface.xml_schema
    - spyne.model
    - spyne.model.primitive
    - spyne.protocol
    - spyne.protocol.cloth
    - spyne.protocol.dictdoc
    - spyne.protocol.html
    - spyne.protocol.soap
    - spyne.server
    - spyne.store
    - spyne.store.relational
    - spyne.test
    - spyne.test.interface
    - spyne.test.interface.wsdl
    - spyne.test.interop
    - spyne.test.interop.server
    - spyne.test.interop.server.soap11
    - spyne.test.interop.server.soap12
    - spyne.test.model
    - spyne.test.multipython
    - spyne.test.multipython.model
    - spyne.test.protocol
    - spyne.test.transport
    - spyne.util
    - spyne.util.oset

about:
  home: http://spyne.io
  license: LGPL-2.1-or-later
  license_file: LICENSE
  summary: A transport and architecture agnostic rpc library that focuses on exposing public services with a well-defined API.

extra:
  recipe-maintainers:
    - ocefpaf
    - emiliom
