appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: SH2C4099Oz04trs/X7wze0XzuAfvyorW7EpL6OXjNHRpfPvn8QWRwV0I6XGOoyXjSQAKsLliCjzm4NmNYDs2B2j7CjGnvHVwzUIVGQUww+nOF1UXYlBuaKlqxTY9aaIWoi9CKxvvghWW6GBpwDbcDIr9KovzW6BYd/51AromwZhIHudwLhuaHxJqkoo4dUrxBfBd5sAvY/6YWaiQ6Rk52PFPB5g6NqLGGTR6Ihukn7WUjvtQ/T4JEljcA2HvC1l0WGvgg+2G5Y7ahsiTzmmcDYMS1Dk4xw9sDrsVS4+Z4FuZJQ9X7Yr63OsuIBC+vyFfmos/+5qg1jzweBe2VfwdpHLXny5aiy6wIxWnNSclMBShEqC3lSaMQUir/uNJAL4k4BARDLB5w1VD5wa9+NnvnP5SfzRKE4H5y94x/z/XeAjZHtodNI3Du7N/qp6ivUJrlcwZFZTzfO5KUSxFR0erx+Df9tKQUQCK1BnWlBJTpUa+9kc8RiNLxc0o4m7U00n5GwdsMZzmPciJN8IDQsM0geJClzRzxrWSPvrl+4/xS+DBwC0aBr6/0Dvm5t1XvtHewCN2/Rq+r+GIahpc/olfzxnfq4ZUzpQFcyE94+Ayvraq2VyPasCKuy4h3D17ktU+7StR6ZoOyU11LcWLJCxEQvKa6RX+eVVO5RGDd7DOSFc=}
provider:
  win: azure
conda_forge_output_validation: true
